[project]
name = "roo-code-chinese-docs"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dotenv>=0.9.9",
    "openai>=2.14.0",
    "requests>=2.32.5",
    "pyyaml>=6.0.1",
]
